"""initialize_database_create_tables

Revision ID: ad70b6681e0e
Revises: 
Create Date: 2022-03-26 22:33:57.386823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad70b6681e0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='The creation time                              of the entry'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='The last modification                               time of the entry'),
    sa.Column('accessed', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='The last time the entry                               was involved in an IDS                               event or scan event'),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('mens', 'womens', name='gender'), nullable=False),
    sa.Column('format', sa.Enum('tests', 'odis', 't20is', name='format'), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('team_name', 'gender', 'format')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
